services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    
    depends_on:
      - server
  
  server:
    build:
      context: ./server
    expose:
      - "8080"
    volumes:
      - ./server/src:/server/src
      - /var/run/docker.sock:/var/run/docker.sock


  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./jellyfin/media:/media
    restart: unless-stopped

  nextcloud:
    image: nextcloud

    expose:
      - "9000"

  # more apps can be added later