FROM maven:3.9-eclipse-temurin-25

WORKDIR /backend

RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*

COPY pom.xml .
RUN mvn dependency:go-offline -q

COPY src ./src

EXPOSE 8080

CMD ["mvn", "spring-boot:run"]